#!/bin/bash
#SBATCH -n 52                                    # number of cores
#SBATCH -t 0-04:00                               # wall time (D-HH:MM)                               # Account hours will be pulled from
#SBATCH -A username
#SBATCH --job-name=indices_mouse_current_release
#SBATCH -o /scratch/username/log_files/indices_mouse_current_release.%j.out   # STDOUT (%j = JobId)
#SBATCH -e /scratch/username/log_files/indices_mouse_current_release.%j.err   # STDERR (%j = JobId)
#SBATCH --mail-type=ALL
#SBATCH --mail-user=username@gmail.com

module load star/2.7.9a

STAR --runThreadN 52 \
--genomeDir /scratch/username/DAVID/index \
--runMode genomeGenerate \
--genomeFastaFiles /scratch/username/DAVID/index/GRCm39.primary_assembly.genome.fa \
--sjdbGTFfile /scratch/username/DAVID/index/gencode.vM27.primary_assembly.annotation.gtf \
--sjdbOverhang 100
